-- =============================================================
--  Migrasi: QRIS statis (GoPay) + keamanan (audit log, bucket privat)
--  Jalankan di Supabase Dashboard > SQL Editor > New Query > Run
-- =============================================================

-- 1. Pengaturan QRIS di app_settings
alter table public.app_settings add column if not exists qris_enabled boolean not null default false;
alter table public.app_settings add column if not exists qris_image_url text;
alter table public.app_settings add column if not exists qris_instructions text;

-- 2. Klaim pembayaran dari pelanggan (alur QRIS: pending -> menunggu verifikasi admin)
alter table public.orders add column if not exists customer_claimed_pay_at timestamptz;

-- 3. Waktu cashback benar-benar dibayarkan ke pelanggan
alter table public.cashback_claims add column if not exists paid_at timestamptz;

-- 4. Tabel audit (riwayat perubahan status oleh admin)
create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  action text not null,
  target_type text,
  target_id text,
  detail text
);

alter table public.audit_logs enable row level security;

-- 5. STORAGE BUCKET cashback-proofs -> PRIVAT
--    (Data tidak boleh bisa diakses publik. Admin hanya melihat bukti lewat
--     signed URL yang dibuat server dengan service role key.)
--    Jalankan di Dashboard > Storage > cashback-proofs > menu (…) > Edit Bucket,
--    ubah "Public" menjadi "Private". Jika ingin via SQL:
-- update storage.buckets set public = false where id = 'cashback-proofs';